### ISSUE TITLE
Test input/output ...

### ISSUE THREAD

**Issue by edwin5588** [genepattern/Tangram#4]
... and see if it matches example notebook outputs

**Comment by omarhalawa3301** [comment]
Achieves same output as the "with_squidpy" notebook (excluding the Deconvolution cells). Should match the "without_squidpy" version (excluding crossval functionality) but might have some issues due to that notebook using older code and dependencies.

**Comment by jkononova3** [comment]
Leaving this issue open for now, would like to test with additional input datasets (referred to by Tangram developers) before closing.

**Comment by omarhalawa3301** [comment]
[This dataset](https://cells.ucsc.edu/?ds=cbl-dev) might be worth considering. Also need to validate the "without_squidpy" notebook.
